'use strict';class l{constructor(a,b){this.x=void 0==a?0:a;this.y=void 0==b?0:b}length(){return Math.hypot(this.x,this.y)}clone(){return new l(this.x,this.y)}};function r(a,b){b|=0;return((a|0)%b+b)%b}function t(a,b,c){return a<b?Math.min(b,a+c):Math.max(b,a-c)}function v(a,b,c,d,e,f,h){null==b&&(b=new l(0,0));let g=a.x+b.x-c.x/2;a=a.y+b.y-c.y/2;return g+c.x>=d&&g<d+f&&a+c.y>=e&&a<e+h};function aa(a,b,c){let d=document.createElement("div");d.setAttribute("style","position: absolute; top: 0; left: 0; z-index: -1;");a.c=document.createElement("canvas");a.c.width=b;a.c.height=c;a.c.setAttribute("style","position: absolute; top: 0; left: 0; z-index: -1;image-rendering: optimizeSpeed;image-rendering: pixelated;image-rendering: -moz-crisp-edges;");d.appendChild(a.c);document.body.appendChild(d);a.C=a.c.getContext("2d");a.C.imageSmoothingEnabled=!1;y(a)}
function y(a){var b=window.innerWidth,c=window.innerHeight;a=a.c;var d=Math.min(b/a.width|0,c/a.height|0);let e=a.width*d;d*=a.height;c=String(c/2-d/2|0)+"px";b=String(b/2-e/2|0)+"px";a.style.width=String(e|0)+"px";a.style.height=String(d|0)+"px";a.style.top=c;a.style.left=b}function D(a,b,c,d){b=void 0==b?255:b;c=void 0==c?b:c;b="rgba("+String(b|0)+","+String(c|0)+","+String((void 0==d?c:d)|0)+",1";a.C.fillStyle=b;a.C.strokeStyle=b}
function E(a,b,c,d,e,f,h,g,u,k,n){if(!(null==b||0>=e||0>=f)){var m=a.C;h+=a.a.x;g+=a.a.y;c|=0;d|=0;e|=0;f|=0;h|=0;g|=0;u|=0;k|=0;n|=0;0!=n&&m.save();0!=(n&1)&&(m.translate(u,0),m.scale(-1,1),h*=-1);0!=(n&2)&&(m.translate(0,k),m.scale(1,-1),g*=-1);m.drawImage(b,c,d,e,f,h,g,u,k);0!=n&&m.restore()}}
class ba{constructor(a,b,c){this.C=this.c=null;aa(this,a,b);this.width=a;this.height=b;window.addEventListener("resize",()=>y(this));this.a=new l(0,0);this.B=null==c?{}:c}clear(a,b,c){this.C.fillStyle="rgba("+String(a|0)+","+String(b|0)+","+String(c|0)+",1";this.C.fillRect(0,0,this.width,this.height)}fillRect(a,b,c,d){a+=this.a.x;b+=this.a.y;this.C.fillRect(a|0,b|0,c|0,d|0)}moveTo(a,b){this.a=new l(a,b)}move(a,b){this.a.x+=a;this.a.y+=b}};function G(a,b){if(null==b)for(b=0;b<a.buttons.length;++b)a.buttons[b]=I;else for(let c=0;c<b.buttons.length;++c){if(c>=a.buttons.length)for(let d=0;d<c-a.buttons.length;++d)a.buttons.push(I);a.buttons[c]=b.buttons[c].pressed?a.buttons[c]==I||a.buttons[c]==J?K:L:a.buttons[c]==L||a.buttons[c]==K?J:I}}
function N(a,b){null!=b&&(a.h.x=0,a.h.y=0,.05<Math.hypot(b.axes[0],b.axes[1])&&(a.h.x=b.axes[0],a.h.y=b.axes[1]),8<=b.axes.length&&.1>Math.hypot(a.h.x,a.h.y)&&.05<Math.hypot(b.axes[6],b.axes[7])&&(a.h.x=b.axes[6],a.h.y=b.axes[7]))}function O(a,b){return null==b||0>b||b>=a.buttons.length?I:a.buttons[b]}
class ca{constructor(){this.h=new l(0,0);this.buttons=[];this.a=null;this.index=0;window.addEventListener("gamepadconnected",a=>{console.log("Gamepad with index "+String(a.gamepad.index)+" connected.");let b=navigator.getGamepads()[a.gamepad.index];this.index=a.gamepad.index;a=this.a=b;N(this,a);G(this,a)})}update(){this.h.x=0;this.h.y=0;if(null!=this.a){var a=navigator;a=null==a?null:a.getGamepads?a.getGamepads():a.webkitGetGamepads?a.webkitGetGamepads:null;null!=a&&(this.a=a[this.index])}a=this.a;
N(this,a);G(this,a)}};var I=0,J=2,L=1,K=3;function P(a,b,c,d,e){a.actions[b]={state:I,key:c,W:d,ja:e};a.i[c]=!0;return a}
function da(a){a.c.update();for(var b in a.actions)a.actions[b].state=a.a[a.actions[b].key]|I,a.actions[b].state==I&&(null!=a.actions[b].W&&(a.actions[b].state=O(a.c,a.actions[b].W)),a.actions[b].state==I&&null!=a.actions[b].ja&&(a.actions[b].state=O(a.c,a.actions[b].ja)));a.f=a.h.clone();b=a.h;b.x=0;b.y=0;.1<a.c.h.length()&&(a.h=a.c.h.clone());a.actions.right.state&1?a.h.x=1:a.actions.left.state&1&&(a.h.x=-1);a.actions.down.state&1?a.h.y=1:a.actions.up.state&1&&(a.h.y=-1);a.j=new l(a.h.x-a.f.x,a.h.y-
a.f.y)}
class ea{constructor(){this.a={};this.i={};this.actions={};this.c=new ca;this.h=new l(0,0);this.f=new l(0,0);this.j=new l(0,0);window.addEventListener("keydown",a=>{var b=a.code;this.a[b]!=L&&(this.a[b]=K);this.i[b]&&a.preventDefault()});window.addEventListener("keyup",a=>{var b=a.code;this.a[b]!=I&&(this.a[b]=J);this.i[b]&&a.preventDefault()});window.addEventListener("contextmenu",a=>{a.preventDefault()});window.addEventListener("mousemove",()=>{window.focus()});window.addEventListener("mousedown",()=>
{window.focus()})}ma(){var a=this.a;for(let b in a)a[b]==K?a[b]=L:a[b]==J&&(a[b]=I)}};class Q{constructor(){}refresh(){}Ca(){}};function R(a,b,c,d){return a.M[b][r(d,a.height)*a.width+r(c,a.width)]}
class fa{constructor(a){a=(new DOMParser).parseFromString(a,"text/xml").getElementsByTagName("map")[0];this.width=String(a.getAttribute("width"));this.height=String(a.getAttribute("height"));let b=a.getElementsByTagName("layer");this.M=[];let c=9999;for(var d of b)d.id<c&&(c=d.id);for(let f=0;f<b.length;++f){d=b[f].id-c;var e=b[f].getElementsByTagName("data")[0].childNodes[0].nodeValue.replace(/(\r\n|\n|\r)/gm,"");e=e.split(",");this.M[d]=[];for(let h=0;h<e.length;++h)this.M[d][h]=parseInt(e[h])}this.a=
{};a=a.getElementsByTagName("properties")[0];if(void 0!=a)for(let f of a.getElementsByTagName("property"))void 0!=f.getAttribute("name")&&(this.a[f.getAttribute("name")]=f.getAttribute("value"))}};class ia{constructor(a,b){this.data=b;this.a=null;this.gain=a.createGain()}play(a,b,c){null!=this.a&&(this.a.disconnect(),this.a=null);let d=a.createBufferSource();d.buffer=this.data;d.loop=!!c;this.gain.gain.value=Math.max(0,Math.min(b,1));d.connect(this.gain).connect(a.destination);d.start(0);this.a=d}stop(){this.a.disconnect();this.a=null}};function ja(a,b){S(a,b,"json",c=>{c=JSON.parse(c);for(let d in c.bitmaps)ka(a,c.bitmaps[d].name,c.bitmapPath+c.bitmaps[d].path);for(let d in c.tilemaps)la(a,c.tilemaps[d].name,c.tilemapPath+c.tilemaps[d].path);for(let d in c.samples)ma(a,c.samples[d].name,c.samplePath+c.samples[d].path)})}
function S(a,b,c,d){let e=new XMLHttpRequest;e.overrideMimeType("text/"+c);e.open("GET",b,!0);++a.total;e.onreadystatechange=()=>{4==e.readyState&&("200"==String(e.status)&&void 0!=d&&d(e.responseText),++a.loaded)};e.send(null)}function ka(a,b,c){++a.total;let d=new Image;d.onload=()=>{++a.loaded;a.B[b]=d};d.src=c}function la(a,b,c){++a.total;S(a,c,"xml",d=>{a.va[b]=new fa(d);++a.loaded})}
function ma(a,b,c){++a.total;let d=new XMLHttpRequest;d.open("GET",c,!0);d.responseType="arraybuffer";d.onload=()=>{a.a.C.decodeAudioData(d.response,e=>{++a.loaded;a.A[b]=new ia(a.a.C,e)})};d.send(null)}function na(a){return 0==a.total||a.loaded>=a.total}class oa{constructor(a){this.B={};this.va={};this.A={};this.loaded=this.total=0;this.a=a}load(a){ja(this,a)}};function T(a,b,c){b.play(a.C,c,!1)}class pa{constructor(){this.C=new AudioContext;this.a=null}};function qa(a,b){var c=b.width/4;let d=c/8;b.clear(0,0,0);a=a.l;var e=0==a.total?0:a.loaded/a.total;a=b.width/2-c/2;let f=b.height/2-d/2;a|=0;f|=0;D(b,255,255,255);b.fillRect(a-2,f-2,c+4,d+4);D(b,0);b.fillRect(a-1,f-1,c+2,d+2);c=c*e|0;D(b,255);b.fillRect(a,f,c,d)}
class ra{constructor(a,b,c){this.c=this.v=0;this.audio=new pa;this.l=new oa(this.audio);this.u=new ba(a,b,this.l.B);this.a={step:c+1,l:this.l,audio:this.audio,input:P(P(P(P(new ea,"left","ArrowLeft",14,null),"up","ArrowUp",12,null),"right","ArrowRight",15,null),"down","ArrowDown",13,null)};this.f=new Q(this.a,null);this.j=!1;this.i=this.f}loop(a){const b=16.66667*this.a.step;this.c+=a-this.v;this.c=Math.min(5*b,this.c);this.v=a;a=this.c/b|0;let c=!0,d=na(this.l);d&&!this.j&&(this.f=new this.i.prototype.constructor(this.a,
null),this.i=null,this.j=!0);for(;0<a--;)c&&da(this.a.input),d&&this.f.refresh(this.a),c&&(this.a.input.ma(),c=!1),this.c-=b;na(this.l)?this.f.Ca(this.u):qa(this,this.u);window.requestAnimationFrame(e=>this.loop(e))}};function U(a,b,c,d,e,f){b|=0;c|=0;d|=0;e|=0;if(c==d)a.f=0,a.a=c,a.c=b;else{a.c!=b&&(a.f=0,a.a=d>c?c:d,a.c=b);if(c<d&&a.a<c||c>d&&a.a>c)a.a=c;a.f+=f;a.f>e&&(c<d?++a.a>d&&(a.a=c):--a.a<d&&(a.a=c),a.f-=e)}}function V(a,b,c){a.a=b;a.c=c;a.f=0}class W{constructor(a,b){this.width=a;this.height=b;this.f=this.c=this.a=0}s(a,b,c,d,e){var f=this.width,h=this.height;E(a,b,this.width*this.a,this.height*this.c,f,h,c,d,f,h,e)}};function X(a){var b=a.speed;b.x=0;b.y=0;a=a.target;a.x=0;a.y=0}
class sa{constructor(a,b){this.b=new l(a,b);this.ha=this.b.clone();this.speed=new l(0,0);this.target=this.speed.clone();this.G=new l(1,1);this.o=new l(0,0);this.u=new l(0,0);this.m=!0;this.I=this.ba=!1;this.g=new W(0,0)}xa(){}ra(){}ma(){}update(a){this.m&&(this.I?this.ba?this.ba=this.m=!1:(this.ha=this.b.clone(),this.ra(a),this.speed.x=t(this.speed.x,this.target.x,this.G.x*a.step),this.speed.y=t(this.speed.y,this.target.y,this.G.y*a.step),this.b.x+=this.speed.x*a.step,this.b.y+=this.speed.y*a.step,
this.ma()):this.xa())}s(){}};function ta(a,b,c,d){if(!(!a.I||a.ka||!a.m||a.ba||0>a.speed.y)){var e=a.b.x+a.o.x-a.D.x/2;e+a.D.x<=b+1||e>=b+16-1||(b=a.o.y+a.D.y/2,e=a.ha.y+b,a.b.y+b>=c-1*d.step&&e<=c+(2+a.speed.y)*d.step&&(a.b.y=c-b,a.pa(),a.speed.y*=-a.ta))}}
function ua(a,b,c,d,e){if(!(!a.I||a.ka||!a.m||a.ba||0>a.speed.x*d)){var f=a.b.y+a.o.y-a.D.y/2;if(!(f+a.D.y<=c+1||f>=c+16-1)){c=a.o.x+a.D.x/2*d;f=a.ha.x+c;var h=a.b.x+c;if(0<d&&h>=b-1*e.step&&f<=b+(2+a.speed.x)*e.step||0>d&&h<=b+1*e.step&&f>=b-(2-a.speed.x)*e.step)a.b.x=b-c,a.sa(d,e),a.speed.x*=-a.wa}}}class Y extends sa{constructor(a,b){super(a,b);this.D=this.u.clone();this.ka=!1;this.ta=this.wa=0}pa(){}sa(){}Aa(){}};class va extends Y{constructor(){super(0,0);this.g=new W(16,16);this.a=!1;this.c=0;this.f=null;this.i=0;this.G=new l(.1,.1);this.D=new l(4,4);this.u=new l(8,8);this.I=this.m=!1}ua(a,b,c,d,e,f){this.b=new l(a,b);this.speed=new l(c,d);this.target=this.speed.clone();this.a=!1;this.c=e;this.f=f;this.i=this.speed.length();this.I=this.m=!0}ra(a){let b=new l(this.b.x-this.f.b.x,this.b.y-this.f.b.y),c=b.length();{let d=b.length();1E-4>d?(b.x=0,b.y=0):(b.x/=d,b.y/=d,b.clone())}this.a?(this.target.x=-b.x*this.i,
this.target.y=-b.y*this.i,8>c&&(this.m=!1)):0>=(this.c-=a.step)&&(this.a=!0);U(this.g,5,1,4,4,a.step);this.ka=this.a}s(a){this.m&&this.g.s(a,a.B.figure,this.b.x-8|0,this.b.y-8|0,0<=this.speed.x?0:1)}sa(){this.a||(this.c=0,this.a=!0)}};function wa(a,b){if(void 0==b.g)return!1;let c=a.F.x*a.width,d=a.F.y*a.height;return b.b.x+b.g.width/2>=c&&b.b.y+b.g.height/2>=d&&b.b.x-b.g.width/2<c+a.width&&b.b.y-b.g.height/2<d+a.height}
class xa{constructor(a,b,c,d,e,f,h){this.b=new l(a,b);this.target=this.b.clone();this.F=this.b.clone();this.width=c;this.height=d;this.da=!1;this.la=this.a=0;this.X=e;this.f=f;this.c=h}move(a,b,c){if(this.da||!this.c&&(0==this.b.x&&0>a||this.b.x==this.X-1&&0<a)||!this.i&&(0==this.b.y&&0>b||this.b.y==this.f-1&&0<b))return 0;this.a=1;this.la=c;this.target.x=this.b.x+a|0;this.target.y=this.b.y+b|0;this.da=!0;return this.c&&0>this.target.x?(this.b.x+=this.X,this.target.x+=this.X,1):this.c&&this.target.x>=
this.X?(this.b.x-=this.X,this.target.x-=this.X,-1):0}update(a){this.da&&(0>=(this.a-=this.la*a.step)?(this.a=0,this.b=this.target.clone(),this.F=this.b.clone(),this.da=!1):(a=this.a,this.F.x=a*this.b.x+(1-a)*this.target.x,this.F.y=a*this.b.y+(1-a)*this.target.y))}setPosition(a,b){this.b=new l(a,b);this.target=this.b.clone();this.F=this.b.clone()}};class ya extends Y{constructor(){super(0,0);this.m=!1;this.g=new W(8,8);this.G=new l(.015,.1);this.ta=this.wa=.75;this.D=new l(4,4);this.o=new l(0,7)}ua(a,b,c,d,e){this.b=new l(a,b);this.speed.x=c;this.speed.y=d;this.target.x=0;this.target.y=4;this.m=!0;V(this.g,4*Math.random()|0,e);this.a=!0}xa(){this.m=!1}s(a){this.m&&this.I&&this.g.s(a,a.B.chips,this.b.x-4,this.b.y+3,0)}pa(){!this.a&&.1>this.speed.y&&(this.m=!1);this.a=!1}};const za=[1,4,8,2,9,6,3,5,12,10,7,13,14,11,15];
function Z(a,b,c){if(b.m&&b.I&&!b.ba){var d=b.b.x/16|0,e=b.b.y/16|0,f=d-2,h=e-2;d+=4;e+=4;for(let z=0;z<a.a.M.length-1;++z)for(let A=h;A<=e;++A)for(let q=f;q<=d;++q){var g=R(a.a,z,q,A);if(0!=g&&(g=a.j.M[0][g-1],null!=g))if(0<g&&g<=za.length)Aa(b,g-1,q,A,c);else{var u=a,k=b,n=g-1,m=q,p=A,M=z;g=c;var B=[2,0,2,8],C=[8,2,0,2],w=[12,8,12,8],x=[8,12,8,12];switch(n){case 15:void 0!=k.ca&&k.ca(16*m,16*p,16,16,g);break;case 16:case 17:case 18:case 19:void 0!=k.Ba&&k.Ba(16*m+B[n-16],16*p+C[n-16],w[n-16],x[n-
16],2,g);break;case 20:case 21:case 22:if(void 0!=k.za&&k.za(16*m,16*p,16,16,g)-1>=n-20){k=u.a;B=m;C=p;B=r(B,k.width);C=r(C,k.height);k.M[M][C*k.width+B]=0;m=16*m+8;p=16*p+8;n-=20;M=Math.random()*Math.PI;C=2*Math.PI/6;for(w=0;6>w;++w){B=M+C*w;k=1.5*Math.random()+1;a:{x=u.f;var F=ya;for(let H of x)if(!H.m){x=H;break a}x.push(new F.prototype.constructor);x=x[x.length-1]}x.ua(m,p,Math.cos(B)*k,Math.sin(B)*k*1.75,n)}T(g.audio,g.l.A["break"],.5);break}Aa(k,14,m,p,g);break;case 27:void 0!=k.ca&&k.ca(16*
m+8,16*p,16,16,g);break;case 29:void 0!=k.na&&k.na(16*m,16*p+8,16,8,g);break;case 30:void 0!=k.na&&k.na(16*m,16*p,16,16,g);break;case 31:ta(k,16*m,16*(p+1),g),void 0!=k.ca&&k.ca(16*m,16*p+8,16,8,g,4)}}}}}
function Aa(a,b,c,d,e){b=za[b|0];1==(b&1)&&ta(a,16*c,16*d,e);if(8==(b&8)){var f=16*c,h=16*(d+1);if(!(!a.I||a.ka||!a.m||a.ba||0<a.speed.y)){var g=a.b.x+a.o.x-a.D.x/2;g+a.D.x<=f+1||g>=f+16-1||(f=a.o.y-a.D.y/2,g=a.ha.y+f,a.b.y+f<=h+1*e.step&&g>=h-(2-a.speed.y)*e.step&&(a.b.y=h-f,a.Aa(),a.speed.y*=-a.ta))}}4==(b&4)&&ua(a,16*(c+1),16*d,-1,e);2==(b&2)&&ua(a,16*c,16*d,1,e)}
class Ba{constructor(a){this.a=a.va.base;this.j=a.va.collisions;this.width=this.a.width;this.height=this.a.height;this.c=this.i=0;this.f=[]}update(a,b){this.i=(this.i+.5*b.step)%96;this.c=(this.c+.125*b.step)%16;for(let c of this.f)c.I=wa(a,c),c.update(b),Z(this,c,b)}s(a,b){let c=(10*b.F.x|0)-1;b=(9*b.F.y|0)-1;let d=(a.width/16|0)+2,e=(a.height/16|0)+2;for(let w=0;w<this.a.M.length-1;++w){{var f=void 0,h=void 0,g=void 0,u=a,k=a.B.tileset,n=w,m=c,p=b,M=d,B=e;const x=[133];for(let F=p;F<p+B;++F)for(let z=
m;z<m+M;++z)if(g=R(this.a,n,z,F),0!=g--)if(x.includes(g)){{let A,q;h=u;f=k;var C=z;let H=g%16|0,ha=g/16|0;switch(g){case 133:A=16*F+(1+Math.round(Math.sin(this.c/16*Math.PI*2))),q=this.c|0,q%2!=A%2&&++H,g=16-q,E(h,f,16*H+q,16*ha,g,16,16*C,A,g,16,0),0<q&&E(h,f,16*H,16*ha,q,16,16*(C+1)-q,A,q,16,0)}}}else h=g%16|0,f=g/16|0,E(u,k,16*h,16*f,16,16,16*z,16*F,16,16,0)}}for(let w of this.f)w.s(a)}};function Ca(a,b){a.K&&(a.c*=-1,a.f=0==a.f?1:0);a.P=!1;a.a=20;X(a);b?a.j||(a.speed.x=1.25*a.c,a.target.x=a.speed.x):a.a+=10;a.aa=b;a.H=0;a.J=0;a.ea=!0;b=a.b.y+2;a.O.x=a.b.x+12*a.c;a.O.y=b;a.fa.x=12;a.fa.y=4}
class Da extends Y{constructor(a,b,c){super(a,b);this.g=new W(16,16);this.ga=new W(16,16);this.f=0;this.G=new l(.1,.15);this.o=new l(0,2);this.u=new l(8,12);this.D=new l(6,12);this.R=!1;this.H=0;this.N=!1;this.S=0;this.T=this.Z=this.j=!1;this.a=this.J=0;this.Y=this.P=this.ea=!1;this.ia=0;this.aa=!1;this.O=new l(0,0);this.fa=new l(0,0);this.v=!1;this.U=0;this.K=!1;this.ya=this.L=0;this.i=new va;this.i.m=!1;this.c=1;this.$=this.V=0;this.progress=c;this.qa=this.oa=!1;this.I=!0}ra(a){this.Z&&!this.j&&
(this.Z=!1);this.c=0==this.f?1:-1;var b=a.input.actions.fire2.state;if(b=b==J||b==I)this.Y&&b?(this.Y=!1,this.ia=0,Ca(this,!0),T(a.audio,a.l.A.powerAttack,.6)):!this.aa&&0<this.a&&10>=this.a&&(this.a=0);if(!(0<this.a||this.v||0<this.$)){this.target.x=1*a.input.h.x;this.target.y=2;this.K&&(this.target.y*=.25);this.G=new l(.1,.15);a:{if(a.input.actions.fire2.state==K){if(!this.j&&!this.T&&!this.R&&.1<a.input.h.y){X(this);this.speed.y=-3;this.target.y=4;this.G.y=.35;this.v=!0;this.U=0;b=this.b.y+8;this.O.x=
this.b.x+this.c;this.O.y=b;this.fa.x=6;this.fa.y=12;T(a.audio,a.l.A.downAttack,.6);b=!0;break a}if(this.P){Ca(this,!1);T(a.audio,a.l.A.sword,.5);b=!0;break a}}b=!1}if(b=!b)this.i.m?b=!1:(this.K&&(this.c*=-1,this.f=0==this.f?1:0),a.input.actions.fire3.state==K?(this.i.ua(this.b.x+4*this.c,this.b.y+2,2*this.c,0,24,this),this.i.ha.x=this.b.x,X(this),this.a=30,this.ea=!1,this.J=this.H=0,T(a.audio,a.l.A["throw"],.6),b=!0):b=!1),b=!b;if(b&&(this.T&&(this.G.x*=.5,this.G.y*=.25,this.target.x*=.5,this.target.y*=
.25,this.K=!1,this.L=0),b=a.input.actions.fire1.state,this.j?(.1<a.input.h.x?this.f=0:-.1>a.input.h.x&&(this.f=1),this.target.y=.5*a.input.h.y,this.target.x=0,b==K&&(.1>a.input.h.y&&(this.H=14),this.Z=this.j=this.N=!1,T(a.audio,a.l.A.jump,.5)),b=!0):b=!1,!b)){b=a.input.actions.fire1.state;if(b==K)if(!this.T&&this.R&&.1<a.input.h.y)this.J=20,T(a.audio,a.l.A.jump,.5);else{if(this.R||0<this.S||!this.N||0<this.L)this.H=(this.N=!this.R&&0>=this.S&&0>=this.L)?8:14,this.R=!1,this.S=0,0<this.L&&(this.speed.x=
-2*this.ya),this.K=!1,this.L=0,this.P=!0,this.qa=!1,T(a.audio,a.l.A.jump,.5)}else b==J&&(0<this.H?this.H=0:0<this.J&&(this.J=0),this.qa=!0);if(this.oa=this.qa&&this.N&&0>=this.a&&this.N&&1==(b&1)&&0>=this.H)this.target.y=.5,this.speed.y=this.target.y}}0<this.a&&this.aa?this.O.x+=this.speed.x*a.step:this.v&&(this.O.y+=this.speed.y*a.step);0<this.H&&(this.speed.y=-2,this.T&&(this.speed.y*=.5),this.H-=a.step);0<this.J&&(this.speed.x=2*this.c,this.target.x=this.speed.x,this.J-=a.step);0<this.S&&(this.S-=
a.step);0<this.L&&(this.L-=a.step);0<this.a&&(this.a-=a.step,!this.aa&&this.ea&&0>=this.a&&(this.Y=!0,T(a.audio,a.l.A.charge,.5)));0<this.U&&0>=(this.U-=a.step)&&(this.v=!1);this.Y&&(this.ia=(this.ia+a.step)%20);0<this.V&&(0<this.$?this.$-=a.step:this.V-=a.step);{b=this.g.a;let c=this.g.c;if(0<this.$)V(this.g,0,5);else if(this.v)V(this.ga,3,4),V(this.g,1,4);else if(0<this.a)V(this.g,0,4),this.aa?U(this.ga,4,7,8,4,a.step):V(this.ga,2,4);else if(0<this.J)V(this.g,4,1);else if(.1<Math.abs(this.target.x)&&
(this.f=0>this.target.x?1:0),this.K)V(this.g,3,1);else if(this.T)0<=this.speed.y&&.1<Math.abs(this.target.x)?U(this.g,3,0,1,10,a.step):(b=0>this.speed.y?2:0,V(this.g,b,3));else if(this.j){if(3!=this.g.c||.1<Math.abs(this.target.y))U(this.g,3,3,4,10,a.step),(this.g.c!=c||this.g.a!=b&&3==this.g.a)&&T(a.audio,a.l.A.climb,.6)}else this.oa?(U(this.g,6,0,3,3,a.step),(this.g.c!=c||this.g.a!=b&&0==this.g.a)&&T(a.audio,a.l.A.flap,.5)):this.R?.1>Math.abs(this.speed.x)&&.1>Math.abs(this.target.x)?V(this.g,0,
0):(b=12-6*Math.abs(this.speed.x),U(this.g,0,1,4,b,a.step)):this.N&&0>this.speed.y?U(this.g,2,0,4,4,a.step):(b=0,.5>Math.abs(this.speed.y)?b=1:0<this.speed.y&&(b=2),V(this.g,b,1))}this.i.update(a);this.T=this.j=!1}ma(){this.K=this.R=!1}s(a){if(!(0<this.V&&0!=Math.floor(this.V/2)%2)){var b=this.g.a;this.Y&&0==Math.floor(this.ia/2)%2&&(b+=5);var c=Math.round(this.b.x-8),d=Math.round(this.b.y-7);0<this.a&&this.ea&&this.ga.s(a,a.B.figure,c+12-24*this.f,d+1,this.f);var e=this.g,f=e.width,h=e.height;E(a,
a.B.figure,e.width*b,e.height*this.g.c,f,h,c,d,f,h,this.f);this.v&&this.ga.s(a,a.B.figure,c+3-6*this.f,d+7,this.f);this.i.s(a)}}pa(){this.R=!0;this.N=!1;this.S=12;.1<this.speed.y&&(this.Z=this.j=!1);this.P=!0;this.v&&0>=this.U&&(this.U=20);this.L=0;this.K=!1}sa(a,b){!this.j&&!this.v&&0>=this.a&&!this.T&&0<this.speed.y&&.1<b.input.h.x*a&&(this.K=!0,this.L=15,this.ya=a,this.P=!0)}Aa(){this.H=0}ca(a,b,c,d,e,f){if(!v(this.b,this.o,this.u,a+4,b,c-8,d))return!1;if(this.Z)return this.P=!0,void 0==f&&(this.j=
!0),!0;c=e.input;(c=0>c.h.y&&-.25<=c.f.y&&-.25>c.j.y)||(e=e.input,c=0<e.h.y&&.25>=e.f.y&&.25<e.j.y);return c?(this.Z=this.j=this.P=!0,this.b.x=a+8,void 0!=f&&(this.b.y=b+f),X(this),!0):!1}na(a,b,c,d){return v(this.b,this.o,this.u,a,b,c,d)?(this.T=!0,this.S=1,this.N=!1,this.J=0,this.P=!0):!1}Ba(a,b,c,d,e,f){if(!(0<this.V))return v(this.b,this.o,this.u,a,b,c,d)?(this.c=this.b.x<a+c/2?1:-1,this.f=0<this.c?0:1,this.V=60,this.$=30,this.target.x=0,this.speed.x=2*-this.c,this.j=!1,this.a=0,this.Y=this.K=
this.v=!1,a=this.progress,a.a=Math.max(0,a.a-e),T(f.audio,f.l.A.hurt,.5),!0):!1}za(a,b,c,d){return(0<this.a&&this.ea||this.v||0<this.U)&&v(this.O,null,this.fa,a,b,c,d)?this.aa||this.v?2:1:0}};class Ea{constructor(a){this.a=null;this.progress=a}update(a,b,c){a.da||(this.a.update(c),Z(b,this.a,c),null!=this.a.i&&Z(b,this.a.i,c));{b=this.a;let d=a.b.x*a.width,e=a.b.y*a.height,f=a.target.x-a.b.x,h=a.target.y-a.b.y,g=(b.u.x+2)*a.la,u=(b.u.y+2)*a.la,k=0,n=0,m;a.da?(b.b.x+=f*g*c.step,b.b.y+=h*u*c.step):(0<b.speed.x&&b.b.x+b.o.x+b.u.x/2>d+a.width?k=1:0>b.speed.x&&b.b.x+b.o.x-b.u.x/2<d?k=-1:0<b.speed.y&&b.b.y+b.o.y+b.u.y/2>e+a.height?n=1:0>b.speed.y&&b.b.y+b.o.y-b.u.y/2<e&&(n=-1),0==k&&0==n||0==
(m=a.move(k,n,.05))||(b.b.x+=m*a.width*a.X));null!=b.i&&b.i.m&&!wa(a,b.i)&&(b.i.m=!1)}}s(a){this.a.s(a)}};class Fa{constructor(){this.a=this.c=6}};class Ga extends Q{constructor(a,b){super(a,b);this.c=new Ba(a.l);this.a=new xa(0,0,160,144,this.c.width/10|0,this.c.height/9|0,!0);this.progress=new Fa;this.f=new Ea(this.progress);var c=this.c;{b=this.f;var d=c.a.M[c.a.M.length-1],e=c.width;c=c.height;let f;for(let h=0;h<c;++h)for(let g=0;g<e;++g)if(f=d[h*e+g]-512,!(0>=f))switch(--f,f){case 0:b.a=new Da(16*g+8,16*h+8,b.progress)}}b=this.f;this.a.setPosition(b.a.b.x/160|0,b.a.b.y/144|0);b=a.audio;a=a.l.A.testTrack;null!=b.a&&(b.a.stop(),b.a=null);
a.play(b.C,.6,!0);b.a=a}refresh(a){this.c.update(this.a,a);this.f.update(this.a,this.c,a);this.a.update(a)}Ca(a){a.moveTo(0,0);var b=this.a,c=r(this.c.i+16*b.F.x,96);a.clear(85,170,255);E(a,a.B.background,16,32,48,48,96,16,48,48,0);b=16*b.F.y|0;a.move(0,-b);for(var d=0;3>d;++d)E(a,a.B.background,0,0,96,32,Math.round(-c+96*d),96,96,32,0);D(a,255,255,255);a.fillRect(0,128,a.width,16);for(c=0;c<a.width/16|0;++c)E(a,a.B.background,0,32,16,32,16*c,144,16,32,0);D(a,0,85,170);a.fillRect(0,176,a.width,Math.max(0,
a.height+b-176));a.move(0,b);c=this.a;a.moveTo(-Math.round(c.F.x*c.width),-Math.round(c.F.y*c.height));this.c.s(a,this.a);this.f.s(a);a.moveTo();c=a.B.font;for(d=0;d<this.progress.c;++d)b=9*(d/2|0),0==d%2&&E(a,c,40,0,8,8,1+b,1,8,8,void 0),this.progress.a>d&&E(a,c,32+d%2*4,0,4,8,1+b+d%2*4,1,4,8,void 0)}};window.onload=()=>{var a=new ra(160,144,0);a.l.load("assets/assets.json");var b=[{name:"fire1",key:"KeyZ",W:0},{name:"fire2",key:"KeyX",W:2},{name:"fire3",key:"KeyC",W:1},{name:"start",key:"Enter",W:9,ja:7},{name:"back",key:"Escape"}];for(let c of b)P(a.a.input,c.name,c.key,c.W,c.ja);a.i=Ga;a.j=!1;a.loop(0)};
